"""Aggiunti campi al modello PlayerStat

Revision ID: 54950543aa4f
Revises: 6abc55eba572
Create Date: 2025-09-07 13:03:51.129000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54950543aa4f'
down_revision = '6abc55eba572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('vote', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fanta_vote', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clean_sheet', sa.Boolean(), nullable=True))
        batch_op.drop_column('fantavoto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fantavoto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('clean_sheet')
        batch_op.drop_column('assists')
        batch_op.drop_column('goals')
        batch_op.drop_column('fanta_vote')
        batch_op.drop_column('vote')
        batch_op.drop_column('is_starter')

    # ### end Alembic commands ###
