"""Aggiunto ondeleteCascade su model PlayerStat

Revision ID: 5c17b2937857
Revises: 
Create Date: 2025-09-09 18:36:16.356883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c17b2937857'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fanta_vote',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('player_stat_match_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'match', ['match_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('player_stat_match_id_fkey'), 'match', ['match_id'], ['id'])
        batch_op.alter_column('fanta_vote',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
