"""Add Player and PlayerStats tables

Revision ID: 6abc55eba572
Revises: 
Create Date: 2025-09-07 12:43:57.204339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abc55eba572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
