"""Aggiunto campo clean_sheet

Revision ID: 82799baf6cd0
Revises: 54950543aa4f
Create Date: 2025-09-07 13:11:15.566391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82799baf6cd0'
down_revision = '54950543aa4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.alter_column('fanta_vote',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('clean_sheet',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.alter_column('clean_sheet',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('fanta_vote',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
