"""Aggiunto ondeleteCascade su model PlayerStat

Revision ID: 967be29aaea1
Revises: 5c17b2937857
Create Date: 2025-09-09 18:53:38.338868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967be29aaea1'
down_revision = '5c17b2937857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('player_team_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('player_stat_player_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'player', ['player_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('player_stat_player_id_fkey'), 'player', ['player_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('player_team_id_fkey'), 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###
